[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'ds-test/=lib/solmate/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@rari-capital/solmate/=lib/solmate/',
    '@sygnum/=node_modules/@sygnum/'
]
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config